# Generated by Django 6.0.7 on 2026-07-22 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.profesor'),
        ),
        migrations.AddField(
            model_name='clase',
            name='profesores',
            field=models.ManyToManyField(related_name='clases', through='academico.ClaseProfesor', to='personas.profesor'),
        ),
    ]
