# Generated by Django 6.0.7 on 2026-07-22 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='usuarios.institucion'),
        ),
        migrations.AddField(
            model_name='clase',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='academico.curso'),
        ),
        migrations.AddField(
            model_name='horario',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.clase'),
        ),
        migrations.AddField(
            model_name='precio',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precios', to='academico.curso'),
        ),
        migrations.AlterUniqueTogether(
            name='claseprofesor',
            unique_together={('profesor', 'clase')},
        ),
    ]
