# Generated by Django 6.0.7 on 2026-07-22 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('inscripciones', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='personas.alumno'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='academico.clase'),
        ),
        migrations.AddField(
            model_name='pago',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='inscripciones.inscripcion'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('alumno', 'clase')},
        ),
    ]
